function reg_x86_64() {
    echo "--------- x86-64 registers in ATT style ---------\n"
    echo "    64-bit   32-bit   16-bit   8-bit"
    echo "00   %rax     %eax     %ax      %al    --  Return Value"
    echo "01   %rbx     %ebx     %bx      %bl    --  Callee Saved"
    echo "02   %rcx     %ecx     %cx      %cl    --  4th Argument"
    echo "03   %rdx     %edx     %dx      %dl    --  3rd Argument"
    echo "04   %rsi     %esi     %si      %sil   --  2nd Argument"
    echo "05   %rdi     %edi     %di      %dil   --  1st Argument"
    echo "06   %rbp     %ebp     %bp      %bpl   --  Callee Saved"
    echo "07   %rsp     %esp     %sp      %spl   --  Stack Pointer"
    echo "08   %r8      %r8d     %r8w     %r8b   --  5th Argument"
    echo "09   %r9      %r9d     %r9w     %r9b   --  6th Argument"
    echo "10   %r10     %r10d    %r10w    %r10b  --  Caller Saved"
    echo "11   %r11     %r11d    %r11w    %r11b  --  Caller Saved"
    echo "12   %r12     %r12d    %r12w    %r12b  --  Callee Saved"
    echo "13   %r13     %r13d    %r13w    %r13b  --  Callee Saved"
    echo "14   %r14     %r14d    %r14w    %r14b  --  Callee Saved"
    echo "15   %r15     %r15d    %r15w    %r15b  --  Callee Saved"
    echo "\n--------- x86-64 registers in ATT style ---------"
}
